name: practica_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_app_3.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true  # Elimina la transparencia en iOS

flutter:
  uses-material-design: true

  assets:
    - assets/animations/welcome.json
    - assets/animations/experience.json
    - assets/animations/startsnow.json
